"""changes

Revision ID: 5bead8ff36a0
Revises: f7983939ddec
Create Date: 2021-11-18 23:39:25.670085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bead8ff36a0'
down_revision = 'f7983939ddec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=2550), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sell')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sell',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sell_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sell_content', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sell_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sell_pkey')
    )
    op.drop_table('articles')
    # ### end Alembic commands ###
