"""changes

Revision ID: 81c2aebb10ff
Revises: 924a45a962ee
Create Date: 2021-11-19 10:13:28.057217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c2aebb10ff'
down_revision = '924a45a962ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('pitches', 'phone_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('phone_num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'phone')
    # ### end Alembic commands ###
