"""changes

Revision ID: 924a45a962ee
Revises: b28bf5592b22
Create Date: 2021-11-19 10:12:13.754751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924a45a962ee'
down_revision = 'b28bf5592b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('whats_phone', sa.Integer(), nullable=True))
    op.drop_column('pitches', 'whats_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('whats_num', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'whats_phone')
    # ### end Alembic commands ###
