"""changes

Revision ID: a8b24ea5248b
Revises: 81c2aebb10ff
Create Date: 2021-11-19 10:14:44.328437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b24ea5248b'
down_revision = '81c2aebb10ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'whats_phone')
    op.drop_column('pitches', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('whats_phone', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
