"""changes

Revision ID: b28bf5592b22
Revises: fe7fbe3326ca
Create Date: 2021-11-19 10:05:13.649247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28bf5592b22'
down_revision = 'fe7fbe3326ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('phone_num', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('whats_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'whats_num')
    op.drop_column('pitches', 'phone_num')
    # ### end Alembic commands ###
